### ISSUE TITLE
lmann add photo

### ISSUE THREAD

**Issue by michaelkirk** [jackpine/jackpine.github.com#17]
get your photo and one line bio in the guild.

**Comment by michaelkirk** [comment]
Raw headshots here: https://www.dropbox.com/sh/7kpmfuc9i48wl1c/AACbt2rXVD9xya8U2Fx6ZTDKa?dl=0

They will need to be resized. Pick your favorite @lauraerinmann. I like the stern one. :+1:

**Comment by michaelkirk** [comment]
Actually, I take it back, they're all pretty good.

Maybe this one is best? Up to you @lauraerinmann 
![img_6279](https://cloud.githubusercontent.com/assets/217057/5796086/fd38212a-9f53-11e4-895b-3b1e699ccb74.jpg)

**Comment by lauraerinmann** [comment]
I think that one is best.  I hate looking at my own pictures.

**Comment by michaelkirk** [comment]
@lauraerinmann where is that pull request?

**Comment by lauraerinmann** [comment]
I have clone the website repo to do that, correct?

**Comment by michaelkirk** [comment]
Yes

**Comment by lauraerinmann** [comment]
It's going to take a minute for me to figure that out.

**Comment by michaelkirk** [comment]
BAM. DONE.

**Comment by lauraerinmann** [comment]
awesome
